add modal window
SlobodianiukDS/foodsta pull request #16
Opened 2022-08-28 17:29 UTC by ViraMesha

2022-08-28 19:37 UTC, SlobodianiukDS requested changes

2022-08-28 19:37 UTC, SlobodianiukDS commented on src/sass/components/_form.scss
> +.form {
Форм уже есть, совмести с имеющимся формом инпутом и добавь на модал-форм то чего не хватвети т.д. 

форм.сцсс проверю после всех совмещений

2022-08-28 19:37 UTC, SlobodianiukDS commented on src/sass/components/_modal.scss
> +        outline: none;
аутлайна нет по дефолту

2022-08-28 19:37 UTC, SlobodianiukDS commented on src/sass/components/_offerings.scss
> +    color: #000000;
этот цвет не нужен использкем основной

2022-08-28 19:37 UTC, SlobodianiukDS commented on src/partials/offerings.html
> +          <div class="backdrop backdrop--is-hidden" data-modal>
закинь модалку в отельный хтмл

2022-08-29 19:20 UTC, ViraMesha commented on src/sass/components/_form.scss
> +.form {
зробила у новій вітці модал

2022-08-29 19:20 UTC, ViraMesha commented on src/sass/components/_modal.scss
> +        outline: none;
прибрала

2022-08-29 19:20 UTC, ViraMesha commented on src/sass/components/_offerings.scss
> +    color: #000000;
done

2022-08-29 19:21 UTC, ViraMesha commented on src/partials/offerings.html
> +          <div class="backdrop backdrop--is-hidden" data-modal>
закинула

2022-08-29 19:44 UTC, SlobodianiukDS approved these changes

2022-08-29 19:44 UTC, merged